package com.genailab.ai.model;

/**
 * Role of a message in an AI conversation.
 *
 * <p>These map to the standard roles used by all major AI providers:
 * <ul>
 *   <li>USER — message sent by the human</li>
 *   <li>ASSISTANT — message generated by the AI model</li>
 *   <li>SYSTEM — instructions that shape the AI's behaviour,
 *       sent before the conversation starts. Not shown to the user.</li>
 * </ul>
 *
 */
public enum AiRole {
    USER,
    ASSISTANT,
    SYSTEM
}